// Mocks generated by Mockito 5.0.10 from annotations
// in challenge_app/test/features/quote/presentation/quote/quote_provider_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:challenge_app/core/providers/loading_provider.dart' as _i6;
import 'package:challenge_app/features/quote/data/models/quote_response.dart'
    as _i3;
import 'package:challenge_app/features/quote/domain/repositories/quote_repository.dart'
    as _i2;
import 'package:challenge_app/features/quote/domain/usecases/quote_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeQuoteRepository extends _i1.Fake implements _i2.QuoteRepository {}

class _FakeQuoteResponse extends _i1.Fake implements _i3.QuoteResponse {}

/// A class which mocks [QuoteUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuoteUsecase extends _i1.Mock implements _i4.QuoteUsecase {
  MockQuoteUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuoteRepository get quoteRepository =>
      (super.noSuchMethod(Invocation.getter(#quoteRepository),
          returnValue: _FakeQuoteRepository()) as _i2.QuoteRepository);
  @override
  set quoteRepository(_i2.QuoteRepository? _quoteRepository) =>
      super.noSuchMethod(Invocation.setter(#quoteRepository, _quoteRepository),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.QuoteResponse> execute() => (super.noSuchMethod(
          Invocation.method(#execute, []),
          returnValue: Future<_i3.QuoteResponse>.value(_FakeQuoteResponse()))
      as _i5.Future<_i3.QuoteResponse>);
}

/// A class which mocks [LoadingProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadingProvider extends _i1.Mock implements _i6.LoadingProvider {
  MockLoadingProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);
  @override
  String get msg =>
      (super.noSuchMethod(Invocation.getter(#msg), returnValue: '') as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  dynamic showLoading({String? msg}) =>
      super.noSuchMethod(Invocation.method(#showLoading, [], {#msg: msg}));
  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
