// Mocks generated by Mockito 5.0.10 from annotations
// in challenge_app/test/features/login/data/repositories/login_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:challenge_app/core/data/api_response.dart' as _i2;
import 'package:challenge_app/features/login/data/services/login_service_imp.dart'
    as _i3;
import 'package:challenge_app/features/login/domain/entities/credentials.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeApiResponse<T> extends _i1.Fake implements _i2.ApiResponse<T> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [LoginServiceImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginServiceImp extends _i1.Mock implements _i3.LoginServiceImp {
  MockLoginServiceImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<String>> attempLogin(
          {_i5.Credentials? credentials}) =>
      (super.noSuchMethod(
              Invocation.method(#attempLogin, [], {#credentials: credentials}),
              returnValue: Future<_i2.ApiResponse<String>>.value(
                  _FakeApiResponse<String>()))
          as _i4.Future<_i2.ApiResponse<String>>);
}
